config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :users, only: [:show]
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :attendings, only: [:create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attending.rb
class Attending < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: "User"

  has_many :attendings, dependent: :destroy
  has_many :attendees, through: :attendings, source: :user, dependent: :destroy
  validates :name, :location, :date, :description, presence: true
  scope :past, -> { where("date < ?", Time.zone.now) }
  scope :upcoming, -> { where("date >= ?", Time.zone.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hosted_events, class_name: "Event", foreign_key: "host_id"

  has_many :attendings # Join Table
  has_many :attended_events, through: :attendings, source: :event 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username ])
  end
end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    attendance = @event.attendings.find_or_create_by(user: current_user)

    if attendance.previously_new_record?
      redirect_to event_path(@event), notice: "You are attending this event!"
    else
      redirect_to event_path(@event), alert: "you are already attending this event"
    end
  end

  
  def destroy
    @event = Event.find(params[:event_id])
    @attending = current_user.attendings.find_by(event: @event)
    
    if @attending
      @attending.destroy
      redirect_to event_path(@event), notice: "You are no longer attending this event."
    else
      redirect_to event_path(@event), alert: "Attendance record not found."
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    # @events = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def new 
    @event = current_user.hosted_events.build
  end

  def create
    @event = current_user.hosted_events.build(event_params)
    if @event.save
      redirect_to user_path(current_user), notice: "Event created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = current_user.hosted_events.find(params[:id])
  end

  def update 
    @event = current_user.hosted_events.find(params[:id])

    if @event.update(event_params)
      redirect_to user_path(current_user), notice: "Event edited successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      redirect_to user_path(current_user), status: :see_other, notice: "Event successfully deleted."
    else
      redirect_to user_path(current_user), alert: "You are not authorized to delete this event."
    end
  end

  private

  def event_params
    params.expect(event: [ :date, :location, :name, :description ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show 
    @user = User.find(params[:id])
    @hosted_events = @user.hosted_events
    @attended_events = @user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.erb
<div class="user-event">
  <%= link_to event_path(event) do %>
    <p><strong><%= event.name %></strong></p>
  <% end %>
  <p>Date: <%= event.date.strftime("%B %d, %Y") %></p>
  <p>Location: <%= event.location %></p>
</div>

app/views/events/_form.html.erb
<div class="flex-center">
    <%= form_with model: event do |form| %>
        <%= form.label :name %><br>
        <%= form.text_field :name %><br><br>
        <%= form.label :location %><br>
        <%= form.text_field :location %><br><br>
        <% event.errors.full_messages_for(:location).each do |message| %>
            <div><%= message %></div>
        <% end %>
        <%= form.label :date %><br>
        <%= form.date_field :date %><br><br>
        <% event.errors.full_messages_for(:date).each do |message| %>
            <div><%= message %></div>
        <% end %>
        <%= form.label :description %><br>
        <%= form.text_area :description %><br><br>
        <%= form.submit %>
    <% end %>
</div>

app/views/events/edit.html.erb
<div class="flex-center">
    <h1>Edit Event</h1>
    <%= render "form", event: @event %>
</div>

app/views/events/index.html.erb
<div class="index-wrapper">
    <h1>Events</h1>
    <div class="event-show">
        <% if @upcoming_events.any? %>
            <h3>Upcoming Events</h1>
            <% @upcoming_events.each do | event | %>
            <div class="event">
                <%= render event %>
            </div>
            <% end %>
        <% end %>
        <% if @past_events.any? %>
            <h3>Past Events</h1>
            <% @past_events.each do | event | %>
            <div class="event">
                <%= render event %>
            </div>
            <% end %>
        <% end %>
        <% unless @upcoming_events.any? || @past_events.any? %>
            <p>No Events yet...</p>
        <% end %>
    </div>

</div>

app/views/events/new.html.erb
<div class="flex-center">
    <h1>Create Event</h1>
    <%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<div class="event-container flex-center">
  <div class="event-show">
    <div class="event-header">
      <h1><%= @event.name %></h1>
      <% if user_signed_in? %>
        <% if @event.attendees.include?(current_user) %>
          <%= button_to "Cancel Attendance", event_attending_path(@event, current_user.attendings.find_by(event: @event)), method: :delete, data: { turbo: false } %>
        <% else %>
          <%= button_to "Attend", event_attendings_path(event_id: @event.id), method: :post, data: { turbo: false } %>
        <% end %> 
      <% else %>
        <%= link_to "Sign in to attend", new_user_session_path %>
      <% end %>
    </div>
    <%= @event.date.strftime("%B %d, %Y") %><br>
    <%= @event.location %><br>
    <%= @event.description %><br>

    <% if @event.attendees.any? %>
        <h2>Attendees</h2>
        <% @event.attendees.each do |attendee| %>
          <%= attendee.username %><br>
        <% end %>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to "All Events", root_path %> 
        <% if user_signed_in? %>
          | <%= link_to "Your Events", user_path(current_user) %>
        <% end %>
      </nav>
      <h1><%= link_to "EventBright", root_path %></h1>
      <div class="login-links">
        <% if user_signed_in? %>
          <%= current_user.username %> |
          <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false } %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Log in", new_user_session_path %>
        <% end %>
      </div>
    </header>
    <div id="flash-modal" class="flash-modal">
      <% flash.each do |key, message| %>
        <div class="flash-message flash-<%= key %>">
          <%= message %>
        </div>
      <% end %>
    </div>
    <%# <p class="notice"><%= notice %></p> 
    <%# <p class="alert"><%= alert %></p> 

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="user-show-wrapper">
    <div class="user-events-header">
        <h1>Your events</h1>
        <%= link_to "Create Event", new_event_path %>
    </div>
    <div class="event-lists-wrapper">

        <div class="user-event-list">
            <div class="title">
            <h2>Your Hosted Events</h2>
            </div>
            <% if @hosted_events.any? %>
                <% @hosted_events.each do |event| %>
                    <div class="host-events">
                        <%= render event %>
                        <%= link_to "Edit event", edit_event_path(event)%>
                    </div>
                <% end %>
            <% else %>
                <p>No events yet...</p>
            <% end %>
        </div>
        <div class="user-event-list">
            <div class="title">
                <h2>Events You're Attending</h2>
            </div>
            <% if @attended_events.any? %>
                <% upcoming = @attended_events.select { |e| e.date >= Time.current } %>
                <% past = @attended_events.select { |e| e.date < Time.current } %>
                <h4>Upcoming events</h4>
                <% if upcoming.any? %>
                    <%= render upcoming %>
                <% else %>
                    <p>No Upcoming events...</p>
                <% end %>
                <h4>Past events</h4>
                <% if past.any? %>
                    <%= render past %>
                <% else %>
                    <p>No Past events...</p>
                <% end %>
            <% else %>
                <p>No events yet...</p>
            <% end %>
        </div>
    </div>
</div>